const truthList = [
  'Siapa nama orang yang terakhir kamu stalking diam-diam?',
  'Pernah suka sama sahabat sendiri? Ceritain dong!',
  'Apa kebohongan terbesar yang pernah kamu bilang ke orang tua?',
  'Siapa orang yang paling bikin kamu baper akhir-akhir ini?',
  'Pernah naksir guru atau kakak kelas? Siapa tuh? 😏',
  'Kalo bisa balikan sama mantan, kamu mau nggak? Jawab jujur ya.',
  'Pernah ghosting orang? Kenapa?',
  'Siapa nama gebetan rahasia kamu?',
  'Apa hal paling memalukan yang pernah kamu alami di sekolah?',
  'Kalau bisa hidup sebagai orang lain sehari, mau jadi siapa?',
  'Pernah mimpi buruk yang bikin kamu takut seharian? Ceritain!',
  'Kalau disuruh nikah muda, setuju atau nggak? Kenapa?',
  'Kapan terakhir kali kamu nangis dan kenapa?',
  'Pernah nggak pura-pura sakit biar gak sekolah?',
  'Siapa orang yang paling kamu kangenin saat ini?',
  'Pernah curi-curi liat hp orang lain? Isi apa yang kamu liat?',
  'Apa hal yang paling kamu takutin tentang masa depan?',
  'Kalau disuruh tinggal di hutan 3 hari, siapa yang kamu ajak?',
  'Pernah ketahuan bohong sama orang tua? Ceritain!',
  'Apa hal paling konyol yang pernah kamu lakuin demi cinta?',
  'Pernah ditolak saat nembak? Ceritain dong!',
  'Kalau bisa ngulang satu hari di masa lalu, hari apa dan kenapa?',
  'Hal paling random yang pernah kamu beli online?',
  'Pernah naksir orang tapi gak pernah berani ngomong? Siapa?',
  'Siapa orang yang selalu bikin kamu senyum gak jelas?',
  'Pernah bilang “aku cinta kamu” tapi bohong?',
  'Pernah suka sama pacar temen? Jujur yaa...',
  'Apa hal yang bikin kamu insecure banget?',
  'Kalau kamu jadi hantu, kamu bakal ganggu siapa duluan?',
  'Siapa orang yang pengen kamu peluk sekarang juga?',
  'Apa makanan paling aneh yang pernah kamu coba?',
  'Pernah malu sendiri gara-gara salah chat?',
  'Siapa teman yang paling ngeselin tapi tetep kamu sayang?',
  'Pernah suka sama orang yang sama sekali gak kamu kenal?',
  'Hal paling konyol yang kamu lakukan demi trending di medsos?',
  'Siapa yang terakhir bikin kamu tersenyum hari ini?',
  'Pernah nggak sengaja ngomong jorok depan orang tua?',
  'Kalau bisa jadi seleb satu hari, siapa yang mau kamu jadi?',
  'Pernah gak curi perhatian gebetan orang lain?',
  'Apa rahasia paling memalukan yang kamu simpan dari teman?',
  'Siapa orang yang bikin kamu sakit hati tapi gak pernah kamu bilang?',
  'Pernah bohong buat libur sekolah? Ceritain!',
  'Siapa yang paling kamu kagumi diam-diam?',
  'Kalau bisa ganti nama, kamu mau nama apa?',
  'Pernah suka sama karakter di anime/game? Siapa?',
  'Apa hal paling lucu yang pernah terjadi di kelasmu?',
  'Siapa yang terakhir kamu nge-tag di story tapi malu?',
  'Pernah gagal total waktu PDKT? Ceritain!',
  'Kalau bisa teleport, kamu mau kemana pertama kali?',
  'Hal paling aneh yang kamu lakukan tengah malam?',
  'Siapa yang paling kamu rindukan tapi jarang ketemu?',
  'Pernah jatuh cinta sama teman online? Ceritain!',
  'Apa hal paling random yang bikin kamu senyum hari ini?',
  'Siapa yang terakhir bikin kamu bete tapi lucu juga?',
  'Pernah salah kirim chat ke gebetan? Ceritain!',
  'Kalau bisa jadi hewan sehari, mau jadi apa?',
  'Hal paling gila yang kamu lakukan karena penasaran?',
  'Siapa yang selalu bikin kamu kesel tapi kamu sayang?',
  'Pernah nge-prank orang tua atau teman? Ceritain!',
  'Apa hal paling memalukan waktu di sekolah?',
  'Siapa orang yang selalu bikin kamu jatuh hati diam-diam?',
  'Kalau bisa punya kekuatan super, mau apa?',
  'Pernah salah kirim chat ke grup tapi bikin heboh?',
  'Hal paling random yang kamu beli tanpa mikir?',
  'Siapa yang paling bikin kamu kaget akhir-akhir ini?',
  'Pernah ketahuan nonton film dewasa? Ceritain!',
  'Siapa teman yang paling bikin kamu ngakak?',
  'Kalau bisa tinggal di luar negeri, mau kemana?',
  'Apa hal paling aneh yang kamu lakukan waktu kecil?',
  'Pernah pura-pura jago padahal nggak ngerti?',
  'Siapa orang yang bikin kamu cemburu diam-diam?',
  'Kalau bisa makan satu makanan terus-menerus, mau apa?',
  'Hal paling konyol yang pernah kamu lakukan di pesta?',
  'Siapa orang yang terakhir bikin kamu gemes?',
  'Pernah ketahuan bohong sama gebetan? Ceritain!',
  'Kalau bisa punya hewan peliharaan unik, mau apa?',
  'Hal paling lucu waktu chatting sama teman?',
  'Siapa yang terakhir bikin kamu kaget banget?',
  'Pernah salah ngomong di depan crush? Ceritain!',
  'Kalau bisa jadi karakter game, siapa yang mau kamu jadi?',
  'Hal paling aneh yang pernah kamu alami di mall?',
  'Siapa orang yang bikin kamu senyum tiap hari tapi gak sadar?',
  'Pernah kebobolan saat main prank sama teman?',
  'Kalau bisa liburan kemana saja sekarang, mau kemana?',
  'Apa hal paling random yang bikin kamu ketawa sendiri?',
  'Siapa teman yang paling kamu rindukan akhir-akhir ini?',
  'Pernah salah kirim foto lucu ke orang yang salah?',
  'Kalau bisa punya satu skill aja, mau apa?',
  'Hal paling aneh yang kamu lakukan gara-gara bosan?',
  'Siapa yang paling bikin kamu canggung saat chat?',
  'Pernah gagal total waktu main game bareng teman?',
  'Kalau bisa balik ke masa kecil, mau ngapain?',
  'Apa hal paling memalukan waktu pertama kali ketemu gebetan?',
  'Siapa yang paling bikin kamu kaget di kelas?',
  'Pernah bikin drama kecil sama teman? Ceritain!',
  'Kalau bisa punya kendaraan super, mau apa?',
  'Hal paling random yang bikin kamu ngakak hari ini?',
  'Siapa orang yang terakhir bikin kamu tersipu malu?',
  'Pernah salah ngomong di grup? Ceritain!',
  'Kalau bisa jadi superhero, mau siapa?',
  'Hal paling aneh yang kamu lakukan waktu libur panjang?',
  'Siapa teman yang selalu bikin kamu heboh tapi senang?',
  'Pernah salah kirim hadiah digital ke orang yang salah?',
  'Apa kebohongan terbesar yang pernah kamu lakukan?',
  'Siapa crush rahasiamu sekarang?',
  'Apa hal paling memalukan yang pernah terjadi padamu?',
  'Siapa temanmu yang paling menyebalkan tapi kamu sayang?',
  'Apa kebiasaan anehmu yang orang lain nggak tahu?',
  'Apa ketakutan terbesar yang kamu miliki?',
  'Pernahkah kamu mencuri sesuatu?',
  'Siapa orang yang paling membuatmu cemburu?',
  'Apa rahasia yang belum pernah kamu ceritakan pada orang tua?',
  'Siapa yang paling sering kamu chat diam-diam?',
  'Pernahkah kamu membohongi sahabatmu?',
  'Apa makanan paling aneh yang pernah kamu makan?',
  'Pernahkah kamu menangis karena film?',
  'Apa kebiasaan yang bikin temanmu kesal?',
  'Siapa orang yang paling kamu kagumi?',
  'Apa momen paling memalukan di sekolah?',
  'Pernahkah kamu jatuh cinta diam-diam?',
  'Siapa guru yang paling kamu takuti?',
  'Apa hal konyol yang kamu lakukan saat sendiri?',
  'Siapa yang paling membuatmu tertawa?',
  'Apa rahasia kecil yang membuatmu bangga?',
  'Pernahkah kamu menyukai orang yang salah?',
  'Siapa temanmu yang paling sering kamu bohongi?',
  'Apa kebohongan kecil yang selalu kamu lakukan?',
  'Pernahkah kamu ditolak cinta?',
  'Siapa orang yang paling membuatmu tersipu?',
  'Apa hal yang selalu membuatmu takut?',
  'Siapa yang paling kamu rindukan saat ini?',
  'Apa hal paling gila yang pernah kamu lakukan untuk cinta?',
  'Siapa teman yang paling bisa dipercaya?',
  'Apa momen paling menegangkan yang kamu alami?',
  'Apa hal paling memalukan yang pernah kamu kirim di chat?',
  'Siapa yang paling membuatmu kecewa?',
  'Pernahkah kamu tertangkap basah berbohong?',
  'Siapa yang paling kamu sayangi tapi belum kamu beri tahu?',
  'Apa kebiasaan rahasia yang bikin kamu malu?',
  'Pernahkah kamu membuat orang lain menangis?',
  'Apa hal yang ingin kamu ubah dari masa lalumu?',
  'Siapa yang paling sering membuatmu tersipu malu?',
  'Apa rahasia yang bisa membuat temanmu terkejut?',
  'Siapa yang paling sering kamu kagumi diam-diam?',
  'Pernahkah kamu iri pada temanmu?',
  'Apa hal konyol yang kamu lakukan untuk menarik perhatian?',
  'Siapa yang paling kamu suka tapi malu bilang?',
  'Apa rahasia kecil yang bikin kamu bahagia?',
  'Pernahkah kamu berpura-pura tidak suka seseorang?',
  'Siapa orang yang paling kamu hormati?',
  'Apa hal yang paling kamu sesali?',
  'Siapa teman yang paling membuatmu kesal tapi tetap kamu sayang?',
  'Apa hal lucu yang pernah terjadi padamu di kelas?',
  'Siapa yang paling membuatmu tersenyum hari ini?',
  'Apa hal rahasia yang hanya kamu ketahui?',
  'Siapa yang paling sering membuatmu cemburu diam-diam?',
  'Pernahkah kamu jatuh cinta pada guru?',
  'Apa mimpi aneh yang paling membekas?',
  'Siapa yang paling kamu rindukan saat ini?',
  'Apa hal kecil yang bisa membuatmu bahagia?',
  'Siapa yang paling membuatmu kagum?',
  'Apa rahasia yang selalu kamu simpan sendiri?',
  'Pernahkah kamu melakukan sesuatu yang salah tapi tidak ketahuan?',
  'Siapa teman yang paling setia menurutmu?',
  'Apa hal paling konyol yang pernah kamu lakukan di rumah?',
  'Siapa yang paling sering kamu pikirkan sebelum tidur?',
  'Apa rahasia kecil yang membuatmu tersipu?',
  'Pernahkah kamu bohong demi kebaikan temanmu?',
  'Siapa yang paling sering membuatmu malu di depan umum?',
  'Apa hal paling lucu yang terjadi saat kamu tidur?',
  'Siapa yang paling kamu sukai tapi malu mengakuinya?',
  'Apa hal yang ingin kamu lakukan tapi belum berani?',
  'Siapa teman yang paling sering bikin kamu kesal?',
  'Apa kebiasaan aneh yang kamu lakukan saat sendiri?',
  'Siapa yang paling membuatmu tersenyum setiap hari?',
  'Apa rahasia masa kecil yang belum pernah kamu ceritakan?',
  'Pernahkah kamu merasa bersalah tanpa alasan?',
  'Siapa yang paling membuatmu takut?',
  'Apa hal paling spontan yang pernah kamu lakukan?',
  'Siapa yang paling membuatmu penasaran saat ini?',
  'Apa hal kecil yang bisa membuatmu tersenyum?',
  'Siapa teman yang paling membuatmu rindu?',
  'Apa hal paling gila yang pernah kamu lakukan di sekolah?',
  'Siapa yang paling sering mengganggumu tapi kamu sayang?',
  'Apa rahasia lucu yang hanya kamu ketahui?',
  'Pernahkah kamu menyesal karena sesuatu yang sepele?',
  'Siapa yang paling membuatmu kaget dengan tingkahnya?',
  'Apa hal konyol yang kamu lakukan saat cemas?',
  'Siapa yang paling kamu kagumi tapi belum kamu beri tahu?',
  'Apa hal paling memalukan saat liburan?',
  'Siapa yang paling sering membuatmu tertawa?',
  'Apa rahasia yang ingin kamu bagikan tapi takut?',
  'Siapa teman yang paling aneh menurutmu?',
  'Apa hal paling lucu yang pernah kamu lihat di rumah?',
  'Siapa yang paling membuatmu iri saat ini?',
  'Apa rahasia paling konyol yang pernah kamu simpan?',
  'Siapa teman yang paling aneh tapi kamu sayang?',
  'Apa hal paling memalukan yang pernah kamu lakukan di publik?',
  'Siapa yang paling sering membuatmu kesal diam-diam?',
  'Apa hal paling spontan yang kamu lakukan baru-baru ini?',
  'Siapa yang paling sering kamu pikirkan sebelum tidur?',
  'Apa hal yang bikin kamu takut tapi lucu sekarang?',
  'Siapa teman yang paling membuatmu tersipu malu?',
  'Apa hal kecil yang bikin kamu tertawa terbahak-bahak?',
  'Siapa yang paling membuatmu bingung saat ini?',
  'Apa hal paling konyol yang pernah kamu lakukan saat bosan?',
  'Siapa yang paling sering membuatmu kaget dengan tingkahnya?',
  'Apa rahasia lucu yang hanya kamu dan temanmu tahu?',
  'Siapa yang paling membuatmu tersenyum saat sedih?',
  'Apa hal memalukan yang terjadi saat kamu bermain game?',
  'Siapa yang paling membuatmu cemburu tapi kamu simpan rahasia?',
  'Apa hal paling gila yang pernah kamu lakukan demi temanmu?',
  'Siapa teman yang paling sering kamu panggil diam-diam?',
  'Apa hal konyol yang pernah kamu lakukan di sekolah?',
  'Siapa yang paling membuatmu terkejut hari ini?',
  'Apa hal lucu yang pernah kamu lihat di rumah temanmu?',
  'Siapa teman yang paling bikin kamu penasaran saat ini?',
  'Apa hal memalukan yang pernah kamu lakukan saat tidur?',
  'Siapa yang paling sering membuatmu tersenyum tanpa alasan?',
  'Apa hal paling aneh yang pernah kamu lakukan di rumah?',
  'Sebutkan kebohongan paling konyol yang pernah kamu lakukan tanpa ketahuan orang tua',
  'Pernah pura-pura sakit untuk kabur dari sekolah atau kerja? Ceritain!',
  'Kalau kamu jadi karakter anime selama sehari, siapa dan kenapa?',
  'Apa hal paling absurd yang pernah kamu katakan waktu lagi panik?',
  'Sebutkan tiga hal yang kamu lakukan diam-diam tapi bikin malu kalau ketahuan',
  'Pernah nyamar jadi orang lain cuma untuk iseng? Ceritain deh',
  'Apa hal paling konyol yang kamu lakukan karena dikejar deadline atau PR?',
  'Pernah ketahuan ngerjain prank tapi salah sasaran? Ceritain!',
  'Jika kamu bisa mengganti suaramu dengan suara hewan sehari, hewan apa dan kenapa?',
  'Sebutkan kebiasaan paling aneh yang kamu lakukan sebelum tidur',
  'Pernah jatuh cinta sama orang yang salah? Ceritain ceritanya!',
  'Apa hal paling memalukan yang terjadi di depan crush-mu?',
  'Kalau kamu jadi raja sehari, apa hal pertama yang bakal kamu lakukan?',
  'Pernah ngirim chat salah ke orang yang salah? Ceritain!',
  'Apa rahasia kecil yang cuma kamu tahu sendiri tapi bikin ketawa kalau diingat?',
  'Pernah nyanyi di kamar mandi dan ketahuan orang lain? Reaksinya gimana?',
  'Sebutkan makanan paling aneh yang pernah kamu makan dan nikmati',
  'Kalau kamu bisa punya kekuatan super, tapi cuma sehari, apa dan kenapa?',
  'Pernah nge-prank teman sampai ketakutan? Ceritain!',
  'Apa hal paling spontan yang pernah kamu lakukan karena bosan?',
  'Kalau bisa ganti nama sendiri, kamu bakal pilih nama apa dan kenapa?',
  'Pernah berbohong demi menghindari PR atau tugas rumah? Ceritain!',
  'Sebutkan kebiasaan aneh yang bikin temanmu geli atau heran',
  'Apa mimpi paling aneh yang pernah kamu ingat?',
  'Kalau bisa hidup di game selama sehari, game apa yang kamu pilih?',
  'Pernah ketahuan menyontek atau curang waktu ujian? Ceritain!',
  'Sebutkan benda paling random yang selalu kamu bawa kemana-mana',
  'Kalau bisa jadi artis terkenal sehari, siapa dan kenapa?',
  'Apa hal paling konyol yang kamu lakukan karena cemburu?',
  'Pernah salah paham sama teman dan bikin gaduh? Ceritain!',
  'Kalau bisa menghapus satu memori, memori apa yang bakal kamu hapus?',
  'Apa kata terakhir yang bikin kamu nyesel karena salah ucap?',
  'Sebutkan mimpi masa kecilmu yang paling aneh atau lucu',
  'Pernah pura-pura tahu sesuatu padahal nggak ngerti sama sekali? Ceritain!',
  'Kalau bisa punya hewan peliharaan ajaib, apa dan kenapa?',
  'Sebutkan tempat paling memalukan yang pernah kamu tertidur di sana',
  'Pernah lupa nama teman sendiri saat disapa? Ceritain!',
  'Kalau bisa teleport sekali ke mana saja, kamu bakal ke mana?',
  'Apa kebiasaan lucu yang bikin keluarga kamu geleng-geleng kepala?',
  'Pernah ikut challenge aneh dan gagal total? Ceritain!',
  'Kalau kamu bisa jadi invisible sehari, apa yang bakal kamu lakukan?',
  'Sebutkan lagu yang bikin kamu selalu ikut nyanyi walau malu',
  'Apa hal paling konyol yang kamu lakukan gara-gara salah paham pesan?',
  'Pernah nggak sengaja memecahkan barang orang lain? Ceritain!',
  'Kalau bisa punya alat canggih apapun, apa yang kamu pilih dan kenapa?',
  'Sebutkan makanan yang kamu benci tapi tetap makan karena terpaksa',
  'Pernah bikin video atau foto aneh dan ketahuan orang lain? Ceritain!',
  'Kalau bisa kembali ke masa lalu sehari, apa yang bakal kamu lakukan?',
  'Apa hal paling random yang bikin kamu tertawa sendirian?',
  'Pernah salah kostum di acara atau pesta? Ceritain!',
  'Kalau bisa tuker hidup dengan teman sehari, siapa dan kenapa?',
  'Sebutkan benda paling absurd yang pernah kamu beli tanpa alasan',
  'Pernah dikira orang lain melakukan hal yang salah padahal kamu? Ceritain!',
  'Kalau bisa bikin hukum sendiri sehari, apa yang bakal kamu buat?',
  'Apa hal paling nyeleneh yang kamu lakukan karena penasaran?',
  'Pernah ketahuan curi makanan? Reaksinya gimana?',
  'Kalau bisa ngobrol dengan hewan, hewan apa yang bakal kamu ajak bicara?',
  'Sebutkan pakaian paling aneh yang pernah kamu pakai di depan umum',
  'Pernah salah kirim voice note ke orang yang salah? Ceritain!',
  'Kalau bisa punya rumah impian di mana saja, seperti apa bentuknya?',
  'Apa kebiasaan paling random yang bikin temanmu kesal tapi kamu senang?',
  'Pernah ngupil ketahuan orang? Ceritain!',
  'Kalau bisa jadi karakter film sehari, siapa dan kenapa?',
  'Sebutkan snack paling aneh yang kamu suka tapi orang lain jijik',
  'Pernah salah paham karena emoji chat? Ceritain!',
  'Kalau bisa makan cuma satu makanan seumur hidup, apa yang kamu pilih?',
  'Apa hal paling gokil yang kamu lakukan di kelas atau kantor?',
  'Pernah ketahuan nonton film dewasa diam-diam? Ceritain!',
  'Kalau bisa jadi super villain sehari, apa yang bakal kamu lakukan?',
  'Sebutkan kata atau frasa yang paling sering bikin kamu ketawa sendiri',
  'Pernah bikin drama kecil karena salah paham? Ceritain!',
  'Kalau bisa menguasai satu bahasa asing dalam semalam, bahasa apa?',
  'Apa hal paling nekat yang pernah kamu lakukan untuk pamer ke teman?',
  'Pernah salah kirim email penting? Ceritain!',
  'Kalau bisa hidup di era manapun, kamu bakal pilih era apa?',
  'Sebutkan benda paling random yang kamu temukan di jalan dan dibawa pulang',
  'Pernah ketahuan tertidur di kelas atau kantor? Ceritain!',
  'Kalau bisa mengubah satu peraturan di sekolah/kerja, apa yang kamu ubah?',
  'Apa hal paling gokil yang kamu lakukan demi memenangkan taruhan?',
  'Pernah salah kirim chat curhat ke grup publik? Ceritain!',
  'Kalau bisa jadi karakter game sehari, siapa dan kenapa?',
  'Sebutkan kebiasaan paling absurd yang bikin orang tua geleng kepala',
  'Pernah ketahuan pura-pura sibuk padahal nggak ngapa-ngapain? Ceritain!',
  'Kalau bisa makan es krim rasa aneh, rasa apa yang bakal kamu coba?',
  'Apa hal paling spontan yang pernah kamu lakukan karena tantangan teman?',
  'Pernah salah baca pesan penting? Ceritain!',
  'Kalau bisa punya satu skill instan, skill apa yang bakal kamu pilih?',
  'Sebutkan hal paling lucu yang pernah terjadi di pesta atau pertemuan keluarga',
  'Pernah ketahuan curhat ke crush? Ceritain!',
  'Kalau bisa bikin alat transportasi super canggih, apa yang bakal kamu buat?',
  'Apa hal paling random yang bikin kamu ketawa sampai sakit perut?',
  'Pernah salah paham karena nada suara chat? Ceritain!',
  'Kalau bisa jadi presiden sehari, apa yang bakal kamu lakukan?',
  'Sebutkan prank paling gokil yang pernah kamu lakukan ke teman',
  'Pernah ketahuan nyolong cemilan? Ceritain!',
  'Kalau bisa hidup di planet lain sehari, planet apa yang bakal kamu pilih?',
  'Apa kebiasaan paling gokil yang bikin temanmu heran tapi kamu senang',
  'Pernah salah paham saat telepon atau video call? Ceritain!',
  'Kalau bisa jadi karakter komik sehari, siapa dan kenapa?'
]

const dareList = [
  'Kirim voice note nyanyi lagu random ke grup!',
  'Tag orang yang paling kamu suka dan bilang "aku suka kamu"',
  'Kirim foto lucu kamu sekarang ke chat ini',
  'Buat status WA paling konyol selama 1 jam',
  'Chat mantan dan bilang "aku kangen"',
  'Ceritain pengalaman paling memalukan ke teman terdekat',
  'Kirim GIF paling absurd ke grup',
  'Pura-pura jadi karakter anime saat chatting selama 10 menit',
  'Tag 3 teman dan bilang "aku lagi kesel nih"',
  'Buat video pendek joget random dan kirim ke grup',
  'Ganti foto profilmu dengan foto paling konyol yang kamu punya',
  'Kirim pesan random tapi cuma pakai emoji selama 1 menit',
  'Tantang teman untuk story challenge dan ikut juga',
  'Buat voice note pura-pura sedih tapi lucu',
  'Kirim meme paling absurd ke chat grup',
  'Ganti nama kontak teman jadi nama lucu selama 1 jam',
  'Tulis caption absurd di story selama 30 menit',
  'Tag teman dan bilang "aku lagi galau berat"',
  'Kirim pesan random ke orang yang nggak kamu kenal tapi sopan',
  'Ceritain rahasia konyol yang jarang orang tahu',
  'Buat video lipsync lagu absurd dan kirim ke grup',
  'Kirim stiker paling random ke chat teman',
  'Tantang teman untuk main game absurd selama 10 menit',
  'Buat status WA dengan kata paling absurd yang bisa kamu pikirkan',
  'Ceritain kejadian paling konyol di sekolah',
  'Kirim voice note pura-pura marah tapi lucu',
  'Tag teman dan bilang "aku penasaran sama rahasiamu"',
  'Buat gambar doodle absurd dan kirim ke grup',
  'Kirim pesan pakai bahasa gaul banget selama 5 menit',
  'Tantang teman untuk ngirim emoji paling banyak',
  'Buat video slow-motion absurd dan kirim ke grup',
  'Kirim meme absurd ke orang yang kamu suka',
  'Ganti foto profil dengan gambar absurd selama 1 jam',
  'Ceritain pengalaman paling awkward di chat',
  'Buat suara hewan dan kirim ke grup',
  'Tag teman dan pura-pura jadi detektif selama 10 menit',
  'Kirim pesan random cuma pakai huruf pertama setiap kata',
  'Buat story WA dengan caption paling absurd',
  'Ceritain pengalaman memalukan saat pertama kali online class',
  'Kirim pesan pura-pura serius tapi lucu',
  'Buat video lipsync dialog absurd film favoritmu',
  'Tag teman dan bilang "aku lagi iseng nih"',
  'Ganti nama grup jadi kata absurd selama 1 jam',
  'Kirim stiker paling konyol ke chat teman',
  'Buat meme absurd dari foto sendiri',
  'Ceritain pengalaman memalukan saat jalan-jalan',
  'Kirim pesan random pakai huruf kapital semua',
  'Buat voice note nyanyi lagu absurd tapi serius',
  'Tag teman dan bilang "aku baru saja kena prank"',
  'Kirim GIF absurd ke orang yang nggak kamu kenal',
  'Buat story WA pura-pura jadi influencer absurd',
  'Ceritain pengalaman paling aneh saat liburan',
  'Kirim pesan absurd pakai bahasa campuran',
  'Tag teman dan bilang "aku lagi misterius"',
  'Buat video absurd pakai filter lucu',
  'Kirim pesan random ke grup tapi cuma pakai emoji makanan',
  'Ganti nama kontak jadi nama karakter anime selama 1 jam',
  'Ceritain pengalaman paling absurd di kelas',
  'Kirim voice note panjang tapi cuma bilang "hallo"',
  'Tag teman dan bilang "aku lagi galau tapi lucu"',
  'Buat story WA pakai kata paling absurd yang kamu tahu',
  'Ceritain pengalaman memalukan saat chatting sama gebetan',
  'Kirim pesan random tapi pakai bahasa kode sendiri',
  'Buat video absurd saat makan sesuatu',
  'Tag teman dan bilang "aku lagi eksperimen"',
  'Kirim meme absurd ke grup teman',
  'Ganti foto profil jadi meme absurd selama 1 jam',
  'Ceritain pengalaman paling konyol waktu PDKT',
  'Kirim voice note pura-pura terkejut tapi lucu',
  'Tag teman dan bilang "aku lagi misterius nih"',
  'Buat story WA pakai filter absurd',
  'Ceritain kejadian paling absurd saat chatting',
  'Kirim pesan random ke teman tapi pakai emoji hewan',
  'Buat video absurd dengan gerakan paling aneh',
  'Tag teman dan bilang "aku lagi nyari perhatian"',
  'Kirim meme absurd ke orang yang kamu suka',
  'Ganti nama grup jadi kata paling absurd selama 1 jam',
  'Ceritain pengalaman paling memalukan waktu sekolah',
  'Kirim voice note panjang tapi cuma bilang "oke"',
  'Tag teman dan bilang "aku lagi konyol"',
  'Buat story WA pakai kata paling random',
  'Ceritain pengalaman absurd saat belajar online',
  'Kirim pesan absurd pakai huruf acak',
  'Buat video absurd saat olahraga',
  'Tag teman dan bilang "aku lagi eksperimen lucu"',
  'Kirim meme absurd ke grup kelas',
  'Ganti foto profil dengan stiker absurd selama 1 jam',
  'Ceritain pengalaman konyol waktu pertama kali kenal teman',
  'Kirim voice note panjang tapi cuma ketawa',
  'Tag teman dan bilang "aku lagi iseng tapi serius"',
  'Buat story WA pakai kata paling absurd dan lucu',
  'Ceritain pengalaman paling random saat main game',
  'Kirim pesan random ke grup tapi pakai emoji transportasi',
  'Buat video absurd pakai filter aneh',
  'Tag teman dan bilang "aku lagi penasaran"',
  'Kirim meme absurd ke teman yang nggak nyangka',
  'Ganti nama kontak jadi kata absurd selama 1 jam',
  'Ceritain pengalaman memalukan saat liburan',
  'Kirim voice note nyanyi lagu absurd tapi lucu',
  'Tag teman dan bilang "aku lagi eksperimen konyol"',
  'Buat story WA pakai kata absurd campuran emoji',
  'Ceritain kejadian paling absurd di mall',
  'Kirim pesan absurd ke grup tapi cuma pakai angka',
  'Buat video absurd dengan musik random',
  'Tag teman dan bilang "aku lagi galau lucu"',
  'Kirimi orang pertama di chatmu foto random lucu.',
  'Bacakan chat terakhirmu seolah itu berita serius.',
  'Berjalan sambil menahan bola di kepala selama 1 menit.',
  'Pura-pura jadi karakter anime favoritmu selama 2 menit.',
  'Tirukan suara temanmu yang paling nyebelin selama 1 menit.',
  'Kirim voice note nyanyi lagu anak-anak ke crushmu.',
  'Buat pose yoga aneh dan suruh temanmu menebak apa itu.',
  'Gambarkan wajah teman sebelahmu di kertas dengan mata tertutup.',
  'Berpura-pura takut pada benda kecil selama 1 menit.',
  'Tirukan adegan drama sinetron Indonesia dengan ekspresi berlebihan.',
  'Buat ekspresi kaget super lebay dan tahan selama 30 detik.',
  'Ganti emoticon terakhir di chatmu dengan emoji aneh tanpa alasan.',
  'Pura-pura jadi penyiar berita di grup selama 1 menit.',
  'Makan makanan random tapi harus sambil menari.',
  'Ceritakan rahasia memalukan dengan suara robot.',
  'Berjalan sambil meniru hewan yang dipilih temanmu.',
  'Tirukan iklan TV dengan dramatis tapi pakai aksen lucu.',
  'Suruh teman menebak apa yang kamu gambarkan sambil mata ditutup.',
  'Nyanyi lagu favorit temanmu tapi dengan suara serak-serak lucu.',
  'Buat gaya selfie paling absurd dan kirim ke grup.',
  'Pura-pura jadi guru dan beri ceramah konyol selama 1 menit.',
  'Lompat sambil menahan tangan temanmu selama 30 detik.',
  'Buat pose superhero di tengah ruangan dan tahan 1 menit.',
  'Tirukan suara hewan campur manusia, temanmu harus menebak.',
  'Buat video lipsync lagu dramatis tapi ekspresinya berlebihan.',
  'Pura-pura tersesat di dalam rumah selama 2 menit.',
  'Buat tarian random di tempat umum sebisa mungkin tanpa malu.',
  'Tirukan karakter game favoritmu sambil bicara konyol.',
  'Berjalan sambil menahan buku di kepala dan jangan jatuh.',
  'Katakan satu kata setiap 5 detik, temanmu harus menebak ceritanya.',
  'Buat ekspresi takut pada bayangan selama 1 menit.',
  'Tirukan suara alien dan ajak teman ngobrol sebentar.',
  'Tulis pesan paling absurd di chat dan kirim ke grup.',
  'Buat suara monster lucu saat temanmu bicara.',
  'Pura-pura terkejut dengan benda paling biasa di sekitarmu.',
  'Buat pose lucu dan tahan sampai temanmu tertawa.',
  'Berjalan seperti zombie di ruangan selama 1 menit.',
  'Tirukan suara telepon lama saat temanmu menelponmu.',
  'Suruh teman menebak gerakan yang kamu lakukan tanpa bicara.',
  'Buat suara dramatis seperti di film horor sambil duduk diam.',
  'Beri nama absurd untuk benda di sekitar dan gunakan selama 5 menit.',
  'Tirukan semua gerakan temanmu selama 1 menit.',
  'Buat tarian absurd dengan musik yang kamu pilih sendiri.',
  'Pura-pura jatuh cinta pada benda di sekitarmu selama 1 menit.',
  'Buat ekspresi kaget berlebihan saat membaca chat random.',
  'Berjalan sambil meniru gaya raja/ratu selama 1 menit.',
  'Tirukan suara robot yang baru belajar meniru manusia.',
  'Suruh temanmu menebak ekspresi wajahmu yang aneh.',
  'Buat suara hewan mix musik random dan tahan 30 detik.',
  'Pura-pura jadi reporter TV dan wawancarai temanmu sebentar.',
  'Buat video dramatis tapi tentang hal paling sepele.',
  'Bicaralah dengan aksen konyol selama 2 menit.',
  'Tirukan karakter anime sambil menjelaskan sesuatu biasa.',
  'Pura-pura takut pada bayangan tanganmu sendiri.',
  'Buat pose ala superhero dan jangan tertawa sampai 1 menit.',
  'Tirukan suara orang ketakutan dengan lebay.',
  'Buat suara alien saat bangun tidur dan kirim ke grup.',
  'Bacakan chat lama temanmu dengan nada super dramatis.',
  'Tirukan karakter kartun favoritmu tapi pakai suara parau.',
  'Suruh teman menebak ekspresi terkejutmu saat melihat benda biasa.',
  'Buat tarian random sambil memegang benda aneh.',
  'Pura-pura jadi raja/ratu dan beri perintah konyol ke temanmu.',
  'Buat suara binatang lucu sambil menari.',
  'Tirukan adegan film horor tapi dengan nada lucu.',
  'Pura-pura menjadi guru dan suruh teman menebak materi absurd.',
  'Bacakan status terakhir temanmu dengan ekspresi lebay.',
  'Buat video lipsync absurd dan kirim ke grup.',
  'Tirukan temanmu sambil menambahkan suara dramatis.',
  'Pura-pura takut pada benda yang paling biasa di sekitarmu.',
  'Berjalan seperti karakter game favoritmu selama 1 menit.',
  'Buat ekspresi gembira berlebihan saat makan sesuatu biasa.',
  'Tirukan suara alien saat menelepon temanmu.',
  'Pura-pura jadi karakter kartun dan berinteraksi dengan temanmu.',
  'Buat pose absurd dan temanmu harus menebak ceritanya.',
  'Bicara dengan aksen aneh selama 1 menit tanpa tertawa.',
  'Buat tarian random tapi harus dramatis.',
  'Pura-pura jatuh cinta pada benda random di ruangan.',
  'Tirukan suara karakter horor tapi lucu.',
  'Buat ekspresi takut berlebihan sambil duduk diam.',
  'Bicara dengan aksen lucu dan temanmu harus menebak kata-katamu.',
  'Tirukan semua gerakan temanmu selama 30 detik.',
  'Buat video lipsync dramatis tentang hal sepele.',
  'Pura-pura jadi reporter TV untuk benda biasa.',
  'Buat tarian absurd sambil menahan benda di tangan.',
  'Tirukan suara binatang campur musik random.',
  'Pura-pura terkejut dengan benda paling sepele di ruangan.',
  'Buat ekspresi lebay saat membaca chat random temanmu.',
  'Tirukan karakter anime favorit tapi dramatis.',
  'Pura-pura takut pada bayangan sendiri selama 1 menit.',
  'Buat suara robot lucu saat temanmu bicara.',
  'Tirukan temanmu tapi dengan suara lebay.',
  'Buat tarian absurd sambil menahan benda random.',
  'Pura-pura jadi raja/ratu dan beri perintah absurd ke temanmu.',
  'Cium pipi orang di sebelahmu.',
  'Kirim chat lucu ke crushmu sekarang.',
  'Lakukan tarian konyol selama 30 detik.',
  'Bacakan status terakhir di WhatsApp dengan suara keras.',
  'Makan sesuatu yang pedas tanpa minum apapun selama 1 menit.',
  'Pura-pura menjadi guru dan beri ceramah singkat 1 menit.',
  'Tunjukkan foto masa kecilmu ke semua orang.',
  'Pura-pura marah selama 1 menit tanpa tertawa.',
  'Tirukan suara hewan selama 30 detik.',
  'Gambarlah wajah temanmu di kertas sambil mata tertutup.',
  'Pilih seseorang dan ajak mereka selfie sekarang juga.',
  'Berjalan seperti robot keliling ruangan 1 menit.',
  'Bersuara seperti karakter kartun favoritmu selama 1 menit.',
  'Pura-pura berbicara bahasa asing selama 1 menit.',
  'Lakukan 10 push-up atau 20 sit-up.',
  'Tirukan aksi idolamu selama 30 detik.',
  'Ceritakan rahasia memalukanmu dengan ekspresi dramatis.',
  'Pakai benda aneh di kepala selama 5 menit.',
  'Cium tangan orang di sebelahmu.',
  'Buat video singkat lipsync lagu lucu.',
  'Berjalan di sekitar ruangan sambil melompat-lompat.',
  'Makan sesuatu dengan mata tertutup.',
  'Bacakan puisi konyol dengan penuh drama.',
  'Berikan pelukan ke orang terdekat tanpa bilang apa-apa.',
  'Ganti pakaian dengan cara lucu (misal baju dalam luar).',
  'Tirukan suara temanmu selama 1 menit.',
  'Buat gerakan dance random selama 1 menit.',
  'Bersuara seperti robot setiap kali bicara selama 5 menit.',
  'Tunjukkan gesture paling lucu saat selfie.',
  'Tulis nama temanmu di wajah dengan spidol (bisa dihapus setelahnya).',
  'Berteriak aku cinta kamu ke arah teman sebelah.',
  'Lakukan pose aneh dan suruh orang lain menebak maksudnya.',
  'Tirukan adegan film terkenal dengan dramatis.',
  'Pura-pura jadi pembawa acara TV 1 menit.',
  'Makan sesuatu yang berbeda rasa (misal manis + asin).',
  'Panggil orang acak di grup chat dan nyanyi 1 lagu untuk mereka.',
  'Lakukan gerakan TikTok populer tapi dengan cara lucu.',
  'Buat suara monster selama 30 detik.',
  'Berjalan sambil menirukan hewan favoritmu.',
  'Pura-pura tersesat dan minta petunjuk 1 menit.'
]

module.exports = { truthList, dareList }